const _skills = {
    html: "html",
    css: "css",
    js: "javaScript",
    ts: "typeScript",
    csharp: "C#",
    tailwind: "tailwind css",
    bootstrap: "bootstrap",
    materialUi: "material ui",
    framerMotion: "framer motion",
    reactjs: "React js",
    redux: "redux toolkit",
    redux: "redux toolkit",
    styledComponents: "styled-compnents",
    reactScroll: "react scroll",
    emailjs: "email js",
    typedJs: "Typed js",
    Three: "Three js",
    reactIntersection: "React intersection observer",
    reactToastify: "React toastify",
    axios: "Axios",
    reactSweetAlert: "React-sweetAlert2",
    swiperjs: "swiper js",
    reactRouter: "react router dom",
    reactMap: "react simple map",
    nodejs: "node js",
    blazor: "blazor",
    git: "git",
    vite: "vite",
};

export default _skills;
